version: "3"

networks:
  golang-boilerplate:
    driver: bridge

#volumes:
#  postgres_data:
#    driver: local

services:
  db:
    image: postgres:13.8
    container_name: "${DB_CONTAINER_NAME}"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: oliver
      POSTGRES_PASSWORD: 123456
    ports:
      - "${POSTGRES_DB_PORT}:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - "./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
    networks:
      - golang-boilerplate

  atlas:
    image: arigaio/atlas:latest
    container_name: "${ATLAS_CONTAINER_NAME}"
#    depends_on:
#      db:
#        condition: service_healthy
    restart: "no"
    volumes:
      - "./migrations/:/migrations"
    links:
      - "db"
    networks:
      - golang-boilerplate

  # backend-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["api"]
  #   depends_on:
  #     - db
  #   restart: always
  #   environment:
  #     POSTGRES_CONNECTION_STRING: "postgres://backend_user:backend_password@db:5432/backend_db?sslmode=disable"
  #   links:
  #     - db
  #   ports:
  #     - '8000:8000'
  #   networks:
  #     - golang-boilerplate
