// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"golang-boilerplate/ent/contract"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// ContractEdge is the edge representation of Contract.
type ContractEdge struct {
	Node   *Contract `json:"node"`
	Cursor Cursor    `json:"cursor"`
}

// ContractConnection is the connection containing edges to Contract.
type ContractConnection struct {
	Edges      []*ContractEdge `json:"edges"`
	PageInfo   PageInfo        `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

func (c *ContractConnection) build(nodes []*Contract, pager *contractPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Contract
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Contract {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Contract {
			return nodes[i]
		}
	}
	c.Edges = make([]*ContractEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ContractEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ContractPaginateOption enables pagination customization.
type ContractPaginateOption func(*contractPager) error

// WithContractOrder configures pagination ordering.
func WithContractOrder(order *ContractOrder) ContractPaginateOption {
	if order == nil {
		order = DefaultContractOrder
	}
	o := *order
	return func(pager *contractPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultContractOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithContractFilter configures pagination filter.
func WithContractFilter(filter func(*ContractQuery) (*ContractQuery, error)) ContractPaginateOption {
	return func(pager *contractPager) error {
		if filter == nil {
			return errors.New("ContractQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type contractPager struct {
	order  *ContractOrder
	filter func(*ContractQuery) (*ContractQuery, error)
}

func newContractPager(opts []ContractPaginateOption) (*contractPager, error) {
	pager := &contractPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultContractOrder
	}
	return pager, nil
}

func (p *contractPager) applyFilter(query *ContractQuery) (*ContractQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *contractPager) toCursor(c *Contract) Cursor {
	return p.order.Field.toCursor(c)
}

func (p *contractPager) applyCursors(query *ContractQuery, after, before *Cursor) *ContractQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultContractOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *contractPager) applyOrder(query *ContractQuery, reverse bool) *ContractQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultContractOrder.Field {
		query = query.Order(direction.orderFunc(DefaultContractOrder.Field.field))
	}
	return query
}

func (p *contractPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultContractOrder.Field {
			b.Comma().Ident(DefaultContractOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Contract.
func (c *ContractQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ContractPaginateOption,
) (*ContractConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newContractPager(opts)
	if err != nil {
		return nil, err
	}
	if c, err = pager.applyFilter(c); err != nil {
		return nil, err
	}
	conn := &ContractConnection{Edges: []*ContractEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = c.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	c = pager.applyCursors(c, after, before)
	c = pager.applyOrder(c, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		c.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := c.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := c.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// ContractOrderFieldVendorID orders Contract by vendor_id.
	ContractOrderFieldVendorID = &ContractOrderField{
		field: contract.FieldVendorID,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.VendorID,
			}
		},
	}
	// ContractOrderFieldStatus orders Contract by status.
	ContractOrderFieldStatus = &ContractOrderField{
		field: contract.FieldStatus,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.Status,
			}
		},
	}
	// ContractOrderFieldStartDate orders Contract by start_date.
	ContractOrderFieldStartDate = &ContractOrderField{
		field: contract.FieldStartDate,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.StartDate,
			}
		},
	}
	// ContractOrderFieldEndDate orders Contract by end_date.
	ContractOrderFieldEndDate = &ContractOrderField{
		field: contract.FieldEndDate,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.EndDate,
			}
		},
	}
	// ContractOrderFieldTotalAmount orders Contract by total_amount.
	ContractOrderFieldTotalAmount = &ContractOrderField{
		field: contract.FieldTotalAmount,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.TotalAmount,
			}
		},
	}
	// ContractOrderFieldRemainingAmount orders Contract by remaining_amount.
	ContractOrderFieldRemainingAmount = &ContractOrderField{
		field: contract.FieldRemainingAmount,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.RemainingAmount,
			}
		},
	}
	// ContractOrderFieldCreatedAt orders Contract by created_at.
	ContractOrderFieldCreatedAt = &ContractOrderField{
		field: contract.FieldCreatedAt,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.CreatedAt,
			}
		},
	}
	// ContractOrderFieldUpdatedAt orders Contract by updated_at.
	ContractOrderFieldUpdatedAt = &ContractOrderField{
		field: contract.FieldUpdatedAt,
		toCursor: func(c *Contract) Cursor {
			return Cursor{
				ID:    c.ID,
				Value: c.UpdatedAt,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f ContractOrderField) String() string {
	var str string
	switch f.field {
	case contract.FieldVendorID:
		str = "VENDOR_ID"
	case contract.FieldStatus:
		str = "STATUS"
	case contract.FieldStartDate:
		str = "START_DATE"
	case contract.FieldEndDate:
		str = "END_DATE"
	case contract.FieldTotalAmount:
		str = "TOTAL_AMOUNT"
	case contract.FieldRemainingAmount:
		str = "REMAINING_AMOUNT"
	case contract.FieldCreatedAt:
		str = "CREATED_AT"
	case contract.FieldUpdatedAt:
		str = "UPDATED_AT"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f ContractOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *ContractOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("ContractOrderField %T must be a string", v)
	}
	switch str {
	case "VENDOR_ID":
		*f = *ContractOrderFieldVendorID
	case "STATUS":
		*f = *ContractOrderFieldStatus
	case "START_DATE":
		*f = *ContractOrderFieldStartDate
	case "END_DATE":
		*f = *ContractOrderFieldEndDate
	case "TOTAL_AMOUNT":
		*f = *ContractOrderFieldTotalAmount
	case "REMAINING_AMOUNT":
		*f = *ContractOrderFieldRemainingAmount
	case "CREATED_AT":
		*f = *ContractOrderFieldCreatedAt
	case "UPDATED_AT":
		*f = *ContractOrderFieldUpdatedAt
	default:
		return fmt.Errorf("%s is not a valid ContractOrderField", str)
	}
	return nil
}

// ContractOrderField defines the ordering field of Contract.
type ContractOrderField struct {
	field    string
	toCursor func(*Contract) Cursor
}

// ContractOrder defines the ordering of Contract.
type ContractOrder struct {
	Direction OrderDirection      `json:"direction"`
	Field     *ContractOrderField `json:"field"`
}

// DefaultContractOrder is the default ordering of Contract.
var DefaultContractOrder = &ContractOrder{
	Direction: OrderDirectionAsc,
	Field: &ContractOrderField{
		field: contract.FieldID,
		toCursor: func(c *Contract) Cursor {
			return Cursor{ID: c.ID}
		},
	},
}

// ToEdge converts Contract into ContractEdge.
func (c *Contract) ToEdge(order *ContractOrder) *ContractEdge {
	if order == nil {
		order = DefaultContractOrder
	}
	return &ContractEdge{
		Node:   c,
		Cursor: order.Field.toCursor(c),
	}
}
