postgres:
  connectionString: $POSTGRES_CONNECTION_STRING

port:
  graphqlPort: $GRAPHQL_PORT_STRING
  grpcClientPort: $GRPC_PORT_CLIENT

secret:
  accessToken: $ACCESS_TOKEN_SECRET
  refreshToken: $REFRESH_TOKEN_SECRET
  adminAccountUsername: $ADMIN_ACCOUNT_USERNAME
  adminAccountPassword: $ADMIN_ACCOUNT_PASSWORD

trivial:
  appName: $TRIVIAL_APP_NAME
  serverHeader: $TRIVIAL_SERVER_HEADER
  playgroundName: $TRIVIAL_PLAYGROUND_NAME