// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"golang-boilerplate/ent/request"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// RequestEdge is the edge representation of Request.
type RequestEdge struct {
	Node   *Request `json:"node"`
	Cursor Cursor   `json:"cursor"`
}

// RequestConnection is the connection containing edges to Request.
type RequestConnection struct {
	Edges      []*RequestEdge `json:"edges"`
	PageInfo   PageInfo       `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

func (c *RequestConnection) build(nodes []*Request, pager *requestPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Request
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Request {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Request {
			return nodes[i]
		}
	}
	c.Edges = make([]*RequestEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &RequestEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// RequestPaginateOption enables pagination customization.
type RequestPaginateOption func(*requestPager) error

// WithRequestOrder configures pagination ordering.
func WithRequestOrder(order *RequestOrder) RequestPaginateOption {
	if order == nil {
		order = DefaultRequestOrder
	}
	o := *order
	return func(pager *requestPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultRequestOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithRequestFilter configures pagination filter.
func WithRequestFilter(filter func(*RequestQuery) (*RequestQuery, error)) RequestPaginateOption {
	return func(pager *requestPager) error {
		if filter == nil {
			return errors.New("RequestQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type requestPager struct {
	order  *RequestOrder
	filter func(*RequestQuery) (*RequestQuery, error)
}

func newRequestPager(opts []RequestPaginateOption) (*requestPager, error) {
	pager := &requestPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultRequestOrder
	}
	return pager, nil
}

func (p *requestPager) applyFilter(query *RequestQuery) (*RequestQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *requestPager) toCursor(r *Request) Cursor {
	return p.order.Field.toCursor(r)
}

func (p *requestPager) applyCursors(query *RequestQuery, after, before *Cursor) *RequestQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultRequestOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *requestPager) applyOrder(query *RequestQuery, reverse bool) *RequestQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultRequestOrder.Field {
		query = query.Order(direction.orderFunc(DefaultRequestOrder.Field.field))
	}
	return query
}

func (p *requestPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultRequestOrder.Field {
			b.Comma().Ident(DefaultRequestOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Request.
func (r *RequestQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...RequestPaginateOption,
) (*RequestConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newRequestPager(opts)
	if err != nil {
		return nil, err
	}
	if r, err = pager.applyFilter(r); err != nil {
		return nil, err
	}
	conn := &RequestConnection{Edges: []*RequestEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = r.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	r = pager.applyCursors(r, after, before)
	r = pager.applyOrder(r, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		r.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := r.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := r.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// RequestOrderFieldContractID orders Request by contract_id.
	RequestOrderFieldContractID = &RequestOrderField{
		field: request.FieldContractID,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.ContractID,
			}
		},
	}
	// RequestOrderFieldVendorID orders Request by vendor_id.
	RequestOrderFieldVendorID = &RequestOrderField{
		field: request.FieldVendorID,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.VendorID,
			}
		},
	}
	// RequestOrderFieldContractorID orders Request by contractor_id.
	RequestOrderFieldContractorID = &RequestOrderField{
		field: request.FieldContractorID,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.ContractorID,
			}
		},
	}
	// RequestOrderFieldAmount orders Request by amount.
	RequestOrderFieldAmount = &RequestOrderField{
		field: request.FieldAmount,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.Amount,
			}
		},
	}
	// RequestOrderFieldStatus orders Request by status.
	RequestOrderFieldStatus = &RequestOrderField{
		field: request.FieldStatus,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.Status,
			}
		},
	}
	// RequestOrderFieldCollectionDate orders Request by collection_date.
	RequestOrderFieldCollectionDate = &RequestOrderField{
		field: request.FieldCollectionDate,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.CollectionDate,
			}
		},
	}
	// RequestOrderFieldCreatedAt orders Request by created_at.
	RequestOrderFieldCreatedAt = &RequestOrderField{
		field: request.FieldCreatedAt,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.CreatedAt,
			}
		},
	}
	// RequestOrderFieldUpdatedAt orders Request by updated_at.
	RequestOrderFieldUpdatedAt = &RequestOrderField{
		field: request.FieldUpdatedAt,
		toCursor: func(r *Request) Cursor {
			return Cursor{
				ID:    r.ID,
				Value: r.UpdatedAt,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f RequestOrderField) String() string {
	var str string
	switch f.field {
	case request.FieldContractID:
		str = "CONTRACT_ID"
	case request.FieldVendorID:
		str = "VENDOR_ID"
	case request.FieldContractorID:
		str = "CONTRACTOR_ID"
	case request.FieldAmount:
		str = "AMOUNT"
	case request.FieldStatus:
		str = "STATUS"
	case request.FieldCollectionDate:
		str = "COLLECTION_DATE"
	case request.FieldCreatedAt:
		str = "CREATED_AT"
	case request.FieldUpdatedAt:
		str = "UPDATED_AT"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f RequestOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *RequestOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("RequestOrderField %T must be a string", v)
	}
	switch str {
	case "CONTRACT_ID":
		*f = *RequestOrderFieldContractID
	case "VENDOR_ID":
		*f = *RequestOrderFieldVendorID
	case "CONTRACTOR_ID":
		*f = *RequestOrderFieldContractorID
	case "AMOUNT":
		*f = *RequestOrderFieldAmount
	case "STATUS":
		*f = *RequestOrderFieldStatus
	case "COLLECTION_DATE":
		*f = *RequestOrderFieldCollectionDate
	case "CREATED_AT":
		*f = *RequestOrderFieldCreatedAt
	case "UPDATED_AT":
		*f = *RequestOrderFieldUpdatedAt
	default:
		return fmt.Errorf("%s is not a valid RequestOrderField", str)
	}
	return nil
}

// RequestOrderField defines the ordering field of Request.
type RequestOrderField struct {
	field    string
	toCursor func(*Request) Cursor
}

// RequestOrder defines the ordering of Request.
type RequestOrder struct {
	Direction OrderDirection     `json:"direction"`
	Field     *RequestOrderField `json:"field"`
}

// DefaultRequestOrder is the default ordering of Request.
var DefaultRequestOrder = &RequestOrder{
	Direction: OrderDirectionAsc,
	Field: &RequestOrderField{
		field: request.FieldID,
		toCursor: func(r *Request) Cursor {
			return Cursor{ID: r.ID}
		},
	},
}

// ToEdge converts Request into RequestEdge.
func (r *Request) ToEdge(order *RequestOrder) *RequestEdge {
	if order == nil {
		order = DefaultRequestOrder
	}
	return &RequestEdge{
		Node:   r,
		Cursor: order.Field.toCursor(r),
	}
}
