// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-boilerplate/ent/auth"
	"golang-boilerplate/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthUpdate is the builder for updating Auth entities.
type AuthUpdate struct {
	config
	hooks    []Hook
	mutation *AuthMutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (au *AuthUpdate) Where(ps ...predicate.Auth) *AuthUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUsername sets the "username" field.
func (au *AuthUpdate) SetUsername(s string) *AuthUpdate {
	au.mutation.SetUsername(s)
	return au
}

// SetPassword sets the "password" field.
func (au *AuthUpdate) SetPassword(s string) *AuthUpdate {
	au.mutation.SetPassword(s)
	return au
}

// SetAccessToken sets the "access_token" field.
func (au *AuthUpdate) SetAccessToken(s string) *AuthUpdate {
	au.mutation.SetAccessToken(s)
	return au
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (au *AuthUpdate) SetNillableAccessToken(s *string) *AuthUpdate {
	if s != nil {
		au.SetAccessToken(*s)
	}
	return au
}

// ClearAccessToken clears the value of the "access_token" field.
func (au *AuthUpdate) ClearAccessToken() *AuthUpdate {
	au.mutation.ClearAccessToken()
	return au
}

// SetRefreshToken sets the "refresh_token" field.
func (au *AuthUpdate) SetRefreshToken(s string) *AuthUpdate {
	au.mutation.SetRefreshToken(s)
	return au
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (au *AuthUpdate) SetNillableRefreshToken(s *string) *AuthUpdate {
	if s != nil {
		au.SetRefreshToken(*s)
	}
	return au
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (au *AuthUpdate) ClearRefreshToken() *AuthUpdate {
	au.mutation.ClearRefreshToken()
	return au
}

// SetUserID sets the "user_id" field.
func (au *AuthUpdate) SetUserID(i int) *AuthUpdate {
	au.mutation.ResetUserID()
	au.mutation.SetUserID(i)
	return au
}

// AddUserID adds i to the "user_id" field.
func (au *AuthUpdate) AddUserID(i int) *AuthUpdate {
	au.mutation.AddUserID(i)
	return au
}

// Mutation returns the AuthMutation object of the builder.
func (au *AuthUpdate) Mutation() *AuthMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	au.defaults()
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AuthUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AuthUpdate) check() error {
	if v, ok := au.mutation.Username(); ok {
		if err := auth.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Auth.username": %w`, err)}
		}
	}
	if v, ok := au.mutation.Password(); ok {
		if err := auth.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Auth.password": %w`, err)}
		}
	}
	return nil
}

func (au *AuthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   auth.Table,
			Columns: auth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: auth.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Username(); ok {
		_spec.SetField(auth.FieldUsername, field.TypeString, value)
	}
	if value, ok := au.mutation.Password(); ok {
		_spec.SetField(auth.FieldPassword, field.TypeString, value)
	}
	if value, ok := au.mutation.AccessToken(); ok {
		_spec.SetField(auth.FieldAccessToken, field.TypeString, value)
	}
	if au.mutation.AccessTokenCleared() {
		_spec.ClearField(auth.FieldAccessToken, field.TypeString)
	}
	if value, ok := au.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if au.mutation.RefreshTokenCleared() {
		_spec.ClearField(auth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := au.mutation.UserID(); ok {
		_spec.SetField(auth.FieldUserID, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedUserID(); ok {
		_spec.AddField(auth.FieldUserID, field.TypeInt, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AuthUpdateOne is the builder for updating a single Auth entity.
type AuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthMutation
}

// SetUsername sets the "username" field.
func (auo *AuthUpdateOne) SetUsername(s string) *AuthUpdateOne {
	auo.mutation.SetUsername(s)
	return auo
}

// SetPassword sets the "password" field.
func (auo *AuthUpdateOne) SetPassword(s string) *AuthUpdateOne {
	auo.mutation.SetPassword(s)
	return auo
}

// SetAccessToken sets the "access_token" field.
func (auo *AuthUpdateOne) SetAccessToken(s string) *AuthUpdateOne {
	auo.mutation.SetAccessToken(s)
	return auo
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableAccessToken(s *string) *AuthUpdateOne {
	if s != nil {
		auo.SetAccessToken(*s)
	}
	return auo
}

// ClearAccessToken clears the value of the "access_token" field.
func (auo *AuthUpdateOne) ClearAccessToken() *AuthUpdateOne {
	auo.mutation.ClearAccessToken()
	return auo
}

// SetRefreshToken sets the "refresh_token" field.
func (auo *AuthUpdateOne) SetRefreshToken(s string) *AuthUpdateOne {
	auo.mutation.SetRefreshToken(s)
	return auo
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableRefreshToken(s *string) *AuthUpdateOne {
	if s != nil {
		auo.SetRefreshToken(*s)
	}
	return auo
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (auo *AuthUpdateOne) ClearRefreshToken() *AuthUpdateOne {
	auo.mutation.ClearRefreshToken()
	return auo
}

// SetUserID sets the "user_id" field.
func (auo *AuthUpdateOne) SetUserID(i int) *AuthUpdateOne {
	auo.mutation.ResetUserID()
	auo.mutation.SetUserID(i)
	return auo
}

// AddUserID adds i to the "user_id" field.
func (auo *AuthUpdateOne) AddUserID(i int) *AuthUpdateOne {
	auo.mutation.AddUserID(i)
	return auo
}

// Mutation returns the AuthMutation object of the builder.
func (auo *AuthUpdateOne) Mutation() *AuthMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthUpdateOne) Select(field string, fields ...string) *AuthUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Auth entity.
func (auo *AuthUpdateOne) Save(ctx context.Context) (*Auth, error) {
	var (
		err  error
		node *Auth
	)
	auo.defaults()
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Auth)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AuthMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthUpdateOne) SaveX(ctx context.Context) *Auth {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AuthUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AuthUpdateOne) check() error {
	if v, ok := auo.mutation.Username(); ok {
		if err := auth.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Auth.username": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Password(); ok {
		if err := auth.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Auth.password": %w`, err)}
		}
	}
	return nil
}

func (auo *AuthUpdateOne) sqlSave(ctx context.Context) (_node *Auth, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   auth.Table,
			Columns: auth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: auth.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Auth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auth.FieldID)
		for _, f := range fields {
			if !auth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Username(); ok {
		_spec.SetField(auth.FieldUsername, field.TypeString, value)
	}
	if value, ok := auo.mutation.Password(); ok {
		_spec.SetField(auth.FieldPassword, field.TypeString, value)
	}
	if value, ok := auo.mutation.AccessToken(); ok {
		_spec.SetField(auth.FieldAccessToken, field.TypeString, value)
	}
	if auo.mutation.AccessTokenCleared() {
		_spec.ClearField(auth.FieldAccessToken, field.TypeString)
	}
	if value, ok := auo.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if auo.mutation.RefreshTokenCleared() {
		_spec.ClearField(auth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := auo.mutation.UserID(); ok {
		_spec.SetField(auth.FieldUserID, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedUserID(); ok {
		_spec.AddField(auth.FieldUserID, field.TypeInt, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Auth{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
