// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"golang-boilerplate/ent/auth"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int   `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// AuthEdge is the edge representation of Auth.
type AuthEdge struct {
	Node   *Auth  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// AuthConnection is the connection containing edges to Auth.
type AuthConnection struct {
	Edges      []*AuthEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *AuthConnection) build(nodes []*Auth, pager *authPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Auth
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Auth {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Auth {
			return nodes[i]
		}
	}
	c.Edges = make([]*AuthEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &AuthEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// AuthPaginateOption enables pagination customization.
type AuthPaginateOption func(*authPager) error

// WithAuthOrder configures pagination ordering.
func WithAuthOrder(order *AuthOrder) AuthPaginateOption {
	if order == nil {
		order = DefaultAuthOrder
	}
	o := *order
	return func(pager *authPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultAuthOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithAuthFilter configures pagination filter.
func WithAuthFilter(filter func(*AuthQuery) (*AuthQuery, error)) AuthPaginateOption {
	return func(pager *authPager) error {
		if filter == nil {
			return errors.New("AuthQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type authPager struct {
	order  *AuthOrder
	filter func(*AuthQuery) (*AuthQuery, error)
}

func newAuthPager(opts []AuthPaginateOption) (*authPager, error) {
	pager := &authPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultAuthOrder
	}
	return pager, nil
}

func (p *authPager) applyFilter(query *AuthQuery) (*AuthQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *authPager) toCursor(a *Auth) Cursor {
	return p.order.Field.toCursor(a)
}

func (p *authPager) applyCursors(query *AuthQuery, after, before *Cursor) *AuthQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultAuthOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *authPager) applyOrder(query *AuthQuery, reverse bool) *AuthQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultAuthOrder.Field {
		query = query.Order(direction.orderFunc(DefaultAuthOrder.Field.field))
	}
	return query
}

func (p *authPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultAuthOrder.Field {
			b.Comma().Ident(DefaultAuthOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Auth.
func (a *AuthQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...AuthPaginateOption,
) (*AuthConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newAuthPager(opts)
	if err != nil {
		return nil, err
	}
	if a, err = pager.applyFilter(a); err != nil {
		return nil, err
	}
	conn := &AuthConnection{Edges: []*AuthEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = a.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	a = pager.applyCursors(a, after, before)
	a = pager.applyOrder(a, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		a.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := a.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := a.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// AuthOrderFieldUsername orders Auth by username.
	AuthOrderFieldUsername = &AuthOrderField{
		field: auth.FieldUsername,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.Username,
			}
		},
	}
	// AuthOrderFieldPassword orders Auth by password.
	AuthOrderFieldPassword = &AuthOrderField{
		field: auth.FieldPassword,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.Password,
			}
		},
	}
	// AuthOrderFieldAccessToken orders Auth by access_token.
	AuthOrderFieldAccessToken = &AuthOrderField{
		field: auth.FieldAccessToken,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.AccessToken,
			}
		},
	}
	// AuthOrderFieldRefreshToken orders Auth by refresh_token.
	AuthOrderFieldRefreshToken = &AuthOrderField{
		field: auth.FieldRefreshToken,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.RefreshToken,
			}
		},
	}
	// AuthOrderFieldUserID orders Auth by user_id.
	AuthOrderFieldUserID = &AuthOrderField{
		field: auth.FieldUserID,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.UserID,
			}
		},
	}
	// AuthOrderFieldCreatedAt orders Auth by created_at.
	AuthOrderFieldCreatedAt = &AuthOrderField{
		field: auth.FieldCreatedAt,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.CreatedAt,
			}
		},
	}
	// AuthOrderFieldUpdatedAt orders Auth by updated_at.
	AuthOrderFieldUpdatedAt = &AuthOrderField{
		field: auth.FieldUpdatedAt,
		toCursor: func(a *Auth) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.UpdatedAt,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f AuthOrderField) String() string {
	var str string
	switch f.field {
	case auth.FieldUsername:
		str = "USERNAME"
	case auth.FieldPassword:
		str = "PASSWORD"
	case auth.FieldAccessToken:
		str = "ACCESS_TOKEN"
	case auth.FieldRefreshToken:
		str = "REFRESH_TOKEN"
	case auth.FieldUserID:
		str = "USER_ID"
	case auth.FieldCreatedAt:
		str = "CREATED_AT"
	case auth.FieldUpdatedAt:
		str = "UPDATED_AT"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f AuthOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *AuthOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("AuthOrderField %T must be a string", v)
	}
	switch str {
	case "USERNAME":
		*f = *AuthOrderFieldUsername
	case "PASSWORD":
		*f = *AuthOrderFieldPassword
	case "ACCESS_TOKEN":
		*f = *AuthOrderFieldAccessToken
	case "REFRESH_TOKEN":
		*f = *AuthOrderFieldRefreshToken
	case "USER_ID":
		*f = *AuthOrderFieldUserID
	case "CREATED_AT":
		*f = *AuthOrderFieldCreatedAt
	case "UPDATED_AT":
		*f = *AuthOrderFieldUpdatedAt
	default:
		return fmt.Errorf("%s is not a valid AuthOrderField", str)
	}
	return nil
}

// AuthOrderField defines the ordering field of Auth.
type AuthOrderField struct {
	field    string
	toCursor func(*Auth) Cursor
}

// AuthOrder defines the ordering of Auth.
type AuthOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *AuthOrderField `json:"field"`
}

// DefaultAuthOrder is the default ordering of Auth.
var DefaultAuthOrder = &AuthOrder{
	Direction: OrderDirectionAsc,
	Field: &AuthOrderField{
		field: auth.FieldID,
		toCursor: func(a *Auth) Cursor {
			return Cursor{ID: a.ID}
		},
	},
}

// ToEdge converts Auth into AuthEdge.
func (a *Auth) ToEdge(order *AuthOrder) *AuthEdge {
	if order == nil {
		order = DefaultAuthOrder
	}
	return &AuthEdge{
		Node:   a,
		Cursor: order.Field.toCursor(a),
	}
}
