// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "contract_id", Type: field.TypeInt},
		{Name: "vendor_id", Type: field.TypeInt},
		{Name: "contractor_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"created", "readyToCollect", "arrangeCollectionDate", "collected"}, Default: "created"},
		{Name: "collection_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RequestsTable,
	}
)

func init() {
	RequestsTable.Annotation = &entsql.Annotation{
		Table: "requests",
	}
}
