// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"golang-boilerplate/ent"
	"time"
)

type CommonReturn interface {
	IsCommonReturn()
	GetIsError() bool
	GetMsgFromDev() string
	GetMsgFromServer() string
}

type ContractReturn struct {
	Data          *ent.Contract `json:"data"`
	IsError       bool          `json:"isError"`
	MsgFromDev    string        `json:"msgFromDev"`
	MsgFromServer string        `json:"msgFromServer"`
}

func (ContractReturn) IsCommonReturn()               {}
func (this ContractReturn) GetIsError() bool         { return this.IsError }
func (this ContractReturn) GetMsgFromDev() string    { return this.MsgFromDev }
func (this ContractReturn) GetMsgFromServer() string { return this.MsgFromServer }

type ContractVendor struct {
	ID              int       `json:"id"`
	Vendor          *Vendor   `json:"vendor"`
	ContractStatus  string    `json:"contractStatus"`
	StartDate       time.Time `json:"startDate"`
	EndDate         time.Time `json:"endDate"`
	RemainingAmount int       `json:"remainingAmount"`
	TotalAmount     int       `json:"totalAmount"`
}

type ContractVendorReturn struct {
	Data          []*ContractVendor `json:"data"`
	IsError       bool              `json:"isError"`
	MsgFromDev    string            `json:"msgFromDev"`
	MsgFromServer string            `json:"msgFromServer"`
}

func (ContractVendorReturn) IsCommonReturn()               {}
func (this ContractVendorReturn) GetIsError() bool         { return this.IsError }
func (this ContractVendorReturn) GetMsgFromDev() string    { return this.MsgFromDev }
func (this ContractVendorReturn) GetMsgFromServer() string { return this.MsgFromServer }

type Vendor struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
